apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: monitoring

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore

  target:
    name: rds-secret

  data:
    - secretKey: host
      remoteRef:
        key: rds-secret
        property: host

    - secretKey: username
      remoteRef:
        key: rds-secret
        property: username

    - secretKey: password
      remoteRef:
        key: rds-secret
        property: password

    - secretKey: database
      remoteRef:
        key: rds-secret
        property: database