apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: de-ai-19

resources:
- ../../base

commonLabels:
  environment: dev

images:
- name: WAS_IMAGE
  newName: 827913617635.dkr.ecr.ap-northeast-1.amazonaws.com/de-ai-19-devops-tf-eks-auto-dev/was
  newTag: c9aba35bd37b
- name: WEB_IMAGE
  newName: 827913617635.dkr.ecr.ap-northeast-1.amazonaws.com/de-ai-19-devops-tf-eks-auto-dev/web
  newTag: c9aba35bd37b
